title: KraftyFx
email: info@kraftyfx.com
description: >-
  The home for documentation on KBar.
url: "https://kraftyfx.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  kraftyfx

remote_theme: just-the-docs/just-the-docs

aux_links:
  "Get KBar":
    - "//aescripts.com/kbar"
  "GitHub":
    - "//github.com/KraftyFX/KraftyFx.github.io"

aux_links_new_tab: true

collections:
  kbar:
    permalink: "/:collection/:path/"
    output: true

  about:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    kbar:
      name: KBar Documentation
    about:
      name: About

plugins:
  - jekyll-seo-tag

exclude:
  - package.json
  - yarn.lock

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
